[package]
name = "xv7-user"
version = "0.1.0"
authors = ["imtsuki <me@qjx.app>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
usyscall = { path = "../xv7-usyscall", package = "xv7-usyscall" }
